version: '3.8'
services:
  spleeter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/app/input:rw
      - ./output:/app/output:rw
      - spleeter_model:/model:rw
      - ./temp:/app/temp:rw
    environment:
      - MODEL_PATH=/model
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=2
      - CUDA_VISIBLE_DEVICES=-1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  spleeter_model:
    driver: local
  temp:
    driver: local
