version: '3.8'
services:
  spleeter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/app/input:rw
      - ./output:/app/output:rw
      - spleeter_model:/model:rw
    environment:
      - MODEL_PATH=/model
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; assert os.path.exists('/model')"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  spleeter_model:
    driver: local
